### ISSUE TITLE
F: Add Batch name to memo field

### ISSUE THREAD

**Issue by KelleyLangkamp** [KingdomFirst/RockAssemblies#3]
The Batch name currently gets written to the Description field. The request was to have it also written to the Memo field.

**Comment by nateh777** [comment]
Which integration was this enhancement request for? Intacct?

**Comment by KelleyLangkamp** [comment]
I honestly have no idea where I got this from. I can't find a slack, rocket chat or email conversation about this change.

**Comment by KelleyLangkamp** [comment]
I figured out where this came from. Yes, it was for Intacct. Can we make it a block setting that can take lava?
